# Generated by Django 4.2 on 2025-06-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0003_remove_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
