# Generated by Django 4.2 on 2025-06-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0004_task_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
